// <auto-generated />
using System;
using FinalAPIDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalAPIDemo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalAPIDemo.Model.Player", b =>
                {
                    b.Property<string>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BbrefID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("int");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("int");

                    b.Property<string>("BirthState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("DeathCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeathDay")
                        .HasColumnType("int");

                    b.Property<int?>("DeathMonth")
                        .HasColumnType("int");

                    b.Property<string>("DeathState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Debut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalGame")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("NameFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameGiven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameLast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetroID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Throws")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
